name: Taster Ključ &reg;
long_name: Taster Ključ &reg; - interfonski dodatak koji zamenjuje vaš ključ od ulaza
description: Taster ključ tm je interfonski dodatak koji zamenjuje vaš ključ od ulaza. Jednostavno postavite vaš digitalni ključ tako što snimite tajni način zvona (npr dugo kratko kratko). Komšije će se čuditi kako imate brze pomagače u kući koji sam otključavaju vrata.
author: TRK INOVACIJE DOO NOVI SAD www.trk-inovacije.com
url: http://tasterkljuc.rs

markdown: redcarpet
pygments: true
