name: Taster Ključ &trade;
long_name: Taster Ključ &trade; - interfonski dodatak koji zamenjuje vaš ključ ili karticu od ulaza u zgradu
description: Taster ključ tm je interfonski dodatak koji zamenjuje vaš ključ ili karticu od ulaza u zgradu. Jednostavno postavite vaš digitalni ključ i snimite tajni način zvona (npr dugo kratko kratko). Komšije će se čuditi kako imate brze pomagače u kući koji vam otključavaju vrata.
author: TRK INOVACIJE DOO NOVI SAD www.trk-inovacije.com
url: http://tasterkljuc.rs

markdown: redcarpet
pygments: true
permalink: /:categories/:title
